### ISSUE TITLE
Unable to check software update after apply misakaX

### ISSUE THREAD

**Issue by Mowd** [straight-tamago/misakaX#38]
After applying a tweak of misakaX, the iPhone can't check software updates.
The only way is to regenerate MobileGestalt(reset) to make software update back again.

**Comment by QuanTrieuPCYT** [comment]
Same issue here, hopefully this can be fixed somehow

**Comment by 34306** [comment]
Uncheck Internal Storage and you're can check back the update

**Comment by DavidAGInnovation** [comment]
I’m still having this issue, even after I deactivated all the tweaks.

**Comment by DavidAGInnovation** [comment]
Okay, I’ve solved it by:

1. Regenerating MobileGestalt.
This messed up the system because the iPhone entered recovery mode, and couldn’t boot up.

2. I updated (not restored) the iPhone with my Mac (iTunes on Windows can do it too).

3. Fortunately, all data remained untouched, and I reapplied the tweaks and didn’t select the Internal Storage option. This way, I’m indeed able to update the software through the iPhone as it can search for updates again.
